# Generated by Django 6.1.1 on 2026-09-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhome', '0003_student_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
